# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1feb2b094902c2e6f130de1435560215cddf79a3d7e5b4e50d300807c8460944788417ac672ef8fdb40f5d31a03a176baabcf2ea091ea632390f4d2bac7e6624

test:
  secret_key_base: 0bb79639443bbe39ece9c64ded9fd1aadb6d3d7b256d92540456ca039459d9e98a95e1b23433de5148a44cdf01f86953b9ac6589e3fef8d1353c3a34ae899769

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
